apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/yeomin4242/42_inception_of_things.git"
    targetRevision: "main" # master 혹은 원하는 브랜치
    path: "dev" # dev 폴더 (Deployment, Service 등 매니페스트 위치)
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
