apiVersion: v1
kind: Service
metadata:
  name: playground-service
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30080
  type: ClusterIP
